export const coupons = {
    SAVE10:{
        name:'SAVE10',
        discount:10
    },
    SAVE20:{
        name:'SAVE20',
        discount:20
    },
    ABCD:{
        name:'ABCD',
        discount:15
    },
    NEW50:{
        name:'NEW50',
        discount:50
    },
    FESTIVE20:{
        name:'FESTIVE20',
        discount:20  
    },
    BIGBILLION40:{
        name:'BIGBILLION40',
        discount:40 
    },
}